max_velocity = 2.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 2.0 #m/s 
is_reversed = false
target_yaw = -90.0 #degrees

[start_pose]
    dataPoint = "AI4"
[end_pose]
    dataPoint = "MP2"
    angle = 0.0

[[internal_points]]
    x = 1.5
    y = 7.76