max_velocity = 4.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -90.0 #degrees

[start_pose]
    dataPoint = "AS1"

[end_pose]
    dataPoint = "W1"
    angle = 120

[[internal_points]]
    x = 3.39
    y = 4.83
