max_velocity = 3.0 #m/s
max_acceleration = 1.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M3"
    dX = -0.5
    dY = 0.0
    angle = 180.0

[end_pose]
    dataPoint = "M5"
    dX = -0.1
    dY = 0.0
    angle = 180.0
    angle = 0.0

[[internal_points]]
    x = 7.0
    y = 2.43

[[internal_points]]
    x = 7.5
    y = 0.85

