max_velocity = 2.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M3"
    angle = 180.0

[end_pose]
    dataPoint = "AS2"
    angle = 180.0

[[internal_points]]
    x = 5.877
    y = 4.293