max_velocity = 4.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M2"
    angle = 180.0

[end_pose]
    dataPoint = "M3"
    angle = 0.0

[[internal_points]]
    x = 7.0
    y = 4.9432845
