max_velocity = 5.0 #m/s
max_acceleration = 4.7 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M3"
    angle = 180.0

[end_pose]
    dataPoint = "MS3"
    angle = 180.0 # 200.0

[[internal_points]]
    x = 5.364 # 5.221
    y = 4.202 # 4.3

[[internal_points]]
    x = 4.0
    y = 5.0

[[internal_points]]
    x = 3.007
    y = 5.113
