max_velocity = 5.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -34.439 #degrees

[start_pose]
    dataPoint = "M4"
    dX = -0.3
    dY = 0.55
    angle = 180.0

[end_pose]
    dataPoint = "NAS4"
    angle = 143.27

[[internal_points]]
    x = 5.56
    y = 1.7

[[internal_points]]
    x = 2.483
    y = 3.154