max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 26.6 #degrees - old 22.0

[start_pose]
    dataPoint = "MI1"
    dX = 0.0
    dY = 0.0
    angle = 0.0
    
[end_pose]
    dataPoint "W1"
    dX = -0.1
    dY = -0.35
    angle = 26.6

[[internal_points]]
    x = 1.9
    y = 6.46