max_velocity = 5.0 #m/s
max_acceleration = 4.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "MI1"

[end_pose]
    dataPoint = "M3"
    dX = -0.2
    dY = 0.0
    
# W2
[[internal_points]]
    x = 3.02 
    y = 5.60 # 5.55

[[internal_points]]
    x = 5.221
    y = 4.3
