max_velocity = 5.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -36.73 #degrees

[start_pose]
    dataPoint = "M5"

[end_pose]
    dataPoint = "NAS4"

[[internal_points]]
    x = 5.021
    y = 1.395
