max_velocity = 5.0 #m/s
max_acceleration = 4.75 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -33.2 #degrees

[start_pose]
    dataPoint = "M5"
    angle = 180.0

[end_pose]
    dataPoint = "NAS1"
    angle = 153.2

[[internal_points]]
    x = 4.8
    y = 1.0
