max_velocity = 4.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M3"

[end_pose]
    dataPoint = "NAS1"

[[internal_points]]
    x = 5.82
    y = 3.74

[[internal_points]]
    x = 3.07
    y = 4.88