max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M3"
    dX = -0.7 # -0.5
    dY = 0.0 # -0.35
    angle = 180.0

[end_pose]
    dataPoint = "MS3"
    angle = 180.0

[[internal_points]]
    x = 5.489
    y = 4.339
