max_velocity = 5.0 #m/s
max_acceleration = 4.4 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "M1"
    dX = -0.2
    angle = 180.0
[end_pose]
    x = 4.0
    y = 5.55
    angle = 180.0

[[internal_points]]
    x = 5.5
    y = 6.75