max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "NAS2"

[end_pose]
    x = 0.0
    y = 0.0

[[internal_points]]
    x = 0.0
    y = 0.0
