max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "NAS2"
    angle = -6.7

[end_pose]
    dataPoint = "M4"
    dX = -0.25 # -0.5
    dY = 0.0
    angle = 0.0

[[internal_points]]
    x = 4.9
    y = 4.34

[[internal_points]]
    x = 6.3 # 6.2
    y = 3.8 # 3.6 


