max_velocity = 2.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -39.14 #degrees

[start_pose]
    dataPoint = "NAI2"

[end_pose]
    dataPoint = "NAS3"
    angle = -39.14

[[internal_points]]
    x = 2.585
    y = 3.371
