max_velocity = 3.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "NAS4"
    angle = 0.0
[end_pose]
    dataPoint = "W3"
    dX = -0.1
    dY = 0.0
    angle = 0.0

[[internal_points]]
    x = 2.2
    y = 4.11