max_velocity = 4.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "NAI1"

[end_pose]
    dataPoint = "M4"
    dX = -0.8
    dY = 0.50
    angle = 0.0


[[internal_points]]
    x = 2.71
    y = 2.8

[[internal_points]]
    x = 5.56
    y = 2.0

[[internal_points]]
    x = 6.99
    y = 2.15

