max_velocity = 5.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "NAI1"

[end_pose]
    dataPoint = "M3"
    dX = -0.5 # -0.7
    dY = 0.0 # -0.3
    angle = 180.0

[[internal_points]]
    x = 3.3
    y = 3.1

[[internal_points]]
    x = 5.221
    y = 4.0
