max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -90.0 #degrees

[start_pose]
    dataPoint = "W1"
    angle = -90.0
[end_pose]
    dataPoint = "W2"
    angle = -90.0

[[internal_points]]
    x = 2.89
    y = 6.275