max_velocity = 2.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = -30.0 #degrees

[start_pose]
    dataPoint = "W2"
    angle = 180.0
[end_pose]
    dataPoint = "W3"
    dX = -0.1
    dY = 0.0 #-0.24
    angle = -30.0

[[internal_points]]
    x = 2.59
    y = 4.93