max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 30.0 #degrees

[start_pose]
    dataPoint "W3"
    angle = -210.0

[end_pose]
    dataPoint "W1"
    angle = 210.0

[[internal_points]]
    x = 5.55
    y = 1.89
    