max_velocity = 5.0 #m/s
max_acceleration = 4.4 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "W1"
    angle = 0.0

[end_pose]
    x = 3.872
    y = 6.0
    dX = -0.5


[[internal_points]]
    x = 3.291
    y = 6.423