max_velocity = 2.0 #m/s
max_acceleration = 2.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 135.0 #degrees

[start_pose]
    dataPoint = "W1"
[end_pose]
    dataPoint = "W1"
    dX = -0.2
    dY = 0.2
    angle = 135.0

[[internal_points]]
    x = 2.99
    y = 7.1