max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint "W3"
    dX = -0.1
    dY = 0.50
    angle = -210.0
[end_pose]
    dataPoint "W2"
    dX = 0.45
    dY = -0.1
    angle = 0.0

[[internal_points]]
    x = 2.0
    y = 5.3