max_velocity = 5.0 #m/s
max_acceleration = 4.4 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "W1"
    dY = 0.1
    dX = 1.0
    angle = 0.0

[end_pose]
    dataPoint = "M1"
    dX = -0.2


[[internal_points]]
    x = 5.72
    y = 7.4