max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint = "W1"
    dY = 0.1
    dX = 1.0
    angle = 0.0
    
[end_pose]
    dataPoint = "W2"
    dY = 0.1
    dX = 0.0
    angle = 0.0

[[internal_points]]
    x = 3.0
    y = 6.1