max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint "W3"
    dX = -0.1
    dY = 0.25
    angle = 150.0
[end_pose]
    dataPoint = "MI1"
    angle = 0.0

[[internal_points]]
    x = 1.99
    y = 4.8