max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    dataPoint "W2"
    dX = 0.25 # .2
    dY = -0.3 # Red - 0.3 | Blue - 0.3 
    angle = 0.0

[end_pose]
    dataPoint = "MI1"
    dX = 0.0
    angle = 180.0

[[internal_points]]
    x = 1.99
    y = 5.55